version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: tc-pedido
      POSTGRES_PASSWORD: postgres
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  app:
   image: ms-pedido:latest
   build:
     dockerfile: Dockerfile
     context: .
   ports:
       - 8080:8080
   depends_on:
       - db
   environment:
       spring.datasource.url: jdbc:postgresql://db:5432/tc-pedido
   pull_policy: always
   restart: on-failure
